(ns beasts.data)

(def all-beasts
  [{:beast-name :ferno 
    :image "images/ferno.jpg"
    :power 212
    :age 288
    :size 465
    :magic-level 180
    :fright-factor 91
    :series 1
    :book 1
    :visible? true
    :card-visible? false}
   {:beast-name :sepron 
    :image "images/sepron.jpg"
    :power 184
    :age 261
    :size 300
    :magic-level 176
    :fright-factor 83
    :series 1
    :book 2
    :visible? true
    :card-visible? false}
   {:beast-name :arcta 
    :image "images/arcta.jpg"
    :power 132
    :age 324
    :size 480
    :magic-level 120
    :fright-factor 65
    :series 1
    :book 3
    :visible? true
    :card-visible? false}
   {:beast-name :tagus 
    :image "images/tagus.jpg"
    :power 73 
    :age 406 
    :size 100
    :magic-level 114
    :fright-factor 58
    :series 1
    :book 4
    :image-visible? true
    :visible? true
    :card-visible? false} 
   {:beast-name :nanook 
    :image "images/nanook.jpg"
    :power 165
    :age 335
    :size 265
    :magic-level 131
    :series 1
    :book 5
    :fright-factor 73
    :visible? true
    :card-visible? false}
   {:beast-name :epos 
    :image "images/epos.jpg"
    :power 242
    :age 457
    :size 240
    :magic-level 192
    :fright-factor 92
    :series 1
    :book 6
    :visible? true
    :card-visible? false}
   {:beast-name :zepha 
    :image "images/zepha.jpg"
    :power 129
    :age 300
    :size 270
    :magic-level 145
    :fright-factor 65
    :series 2
    :book 1
    :visible? true
    :card-visible? false}
   {:beast-name :claw 
    :image "images/claw.jpg"
    :power 217
    :age 465
    :size 200
    :magic-level 134
    :fright-factor 68
    :series 2
    :book 2
    :visible? true
    :card-visible? false}
   {:beast-name :soltra 
    :image "images/zoltra.jpg"
    :power 196
    :age 487
    :size 107
    :magic-level 184
    :fright-factor 72
    :series 2
    :book 3
    :visible? true
    :card-visible? false}
   {:beast-name :vipero 
    :image "images/vipero.jpg"
    :power 272
    :age 397
    :size 260
    :magic-level 123
    :fright-factor 75
    :series 2
    :book 4
    :visible? true
    :card-visible? false}
  {:beast-name :arachnid 
   :image "images/arachnid.jpg"
   :power 156
   :age 255
   :size 268
   :magic-level 142
   :fright-factor 78
   :series 2
   :book 5
   :visible? true
   :card-visible? false}
  {:beast-name :trillion 
   :image "images/trillion.jpg"
   :power 202
   :age 303
   :size 115
   :magic-level 193
   :fright-factor 85
   :series 2
   :book 6
   :visible? true
   :card-visible? false}
  {:beast-name :torgor 
   :image "images/torgor.jpg"
   :power 210
   :age 224
   :size 144
   :magic-level 126
   :fright-factor 74
   :series 3
   :book 1
   :visible? true
   :card-visible? false}
  {:beast-name :skor 
   :image "images/skor.jpg"
   :power 221
   :age 264
   :size 160
   :magic-level 132
   :fright-factor 78
   :series 3
   :book 2
   :visible? true
   :card-visible? false}
  {:beast-name :narga 
   :image "images/narga.jpg"
   :power 233
   :age 346
   :size 310
   :magic-level 146
   :fright-factor 87
   :series 3
   :book 3
   :visible? true
   :card-visible? false}
  {:beast-name :kaymon 
   :image "images/kaymon.jpg"
   :power 239
   :age 296
   :size 152
   :magic-level 157
   :fright-factor 85
   :series 3
   :book 4
   :visible? true
   :card-visible? false}
  {:beast-name :tusk 
   :image "images/tusk.jpg"
   :power 243
   :age 310
   :size 296
   :magic-level 161
   :fright-factor 70
   :series 3
   :book 5
   :visible? true
   :card-visible? false}
  {:beast-name :sting 
   :image "images/sting.jpg"
   :power 248
   :age 15
   :size 100
   :magic-level 162
   :fright-factor 71
   :series 3
   :book 6
   :visible? true
   :card-visible? false}
  {:beast-name :nixa 
   :image "images/nixa.jpg"
   :power 208
   :age 259
   :size 160
   :magic-level 176
   :fright-factor 90
   :series 4
   :book 1
   :visible? true
   :card-visible? false}
  {:beast-name :equinus 
   :image "images/equinus.jpg"
   :power 148
   :age 310
   :size 160
   :magic-level 181
   :fright-factor 85
   :series 4
   :book 2
   :visible? true
   :card-visible? false}
  {:beast-name :rashouk 
   :image "images/rashouk.jpg"
   :power 165
   :age 321
   :size 300
   :magic-level 154
   :fright-factor 81
   :series 4
   :book 3
   :visible? true
   :card-visible? false}
  {:beast-name :luna 
   :image "images/luna.jpg"
   :power 209
   :age 257
   :size 132
   :magic-level 183
   :fright-factor 84
   :series 4
   :book 4
   :visible? true
   :card-visible? false}
  {:beast-name :blaze 
   :image "images/blaze.jpg"
   :power 210
   :age 313
   :size 320
   :magic-level 187
   :fright-factor 90
   :series 4
   :book 5
   :visible? true
   :card-visible? false}
  {:beast-name :stealth 
   :image "images/stealth.jpg"
   :power 199
   :age 243
   :size 155
   :magic-level 150
   :fright-factor 89
   :series 4
   :book 6
   :visible? true
   :card-visible? false}
  {:beast-name :targro 
   :image "images/targro.jpg"
   :power 232
   :age 370
   :size 268
   :magic-level 134
   :fright-factor 89
   :series 13
   :book 2
   :visible? true
   :card-visible? false}])
